#STAGE1
FROM node:latest as builder
WORKDIR /onlineBusAdmin/src/
COPY . .
RUN npm i
RUN npm run build --prod

#STAGE2
FROM nginx:alpine
COPY --from=builder /onlineBusAdmin/dist/onlineBusAdmin/ /usr/share/nginx/html



