#STAGE1
FROM node:latest as builder
WORKDIR /onlineBusAdmin
COPY . .
RUN npm install
RUN npm run build --prod

#STAGE2
FROM nginx:alpine
COPY --from=builder /dist/onlineBusAdmin/ /usr/share/nginx/html


